apiVersion: v1
kind: Secret
metadata:
  name: opsgenie-cert-monitor-apikey
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  apiKey: {{ .Values.opsgenie.apikey | quote }}
  team: {{ .Values.opsgenie.team | quote }}
