{{- if and .Values.opsgenie .Values.opsgenie.apikey }}
apiVersion: v1
kind: Secret
metadata:
  name: opsgenie-cert-monitor-apikey
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  apiKey: {{ .Values.opsgenie.apikey | quote }}
  {{- if .Values.opsgenie.team }}
  team: {{ .Values.opsgenie.team | quote }}
  {{- end }}
{{- end }}
