# templates/metrics-service.yaml
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.service.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.service.port }}
  selector:
    control-plane: controller-manager
{{- end }}
