//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAccessQuery) DeepCopyInto(out *KafkaAccessQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAccessQuery.
func (in *KafkaAccessQuery) DeepCopy() *KafkaAccessQuery {
	if in == nil {
		return nil
	}
	out := new(KafkaAccessQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaAccessQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAccessQueryList) DeepCopyInto(out *KafkaAccessQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaAccessQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAccessQueryList.
func (in *KafkaAccessQueryList) DeepCopy() *KafkaAccessQueryList {
	if in == nil {
		return nil
	}
	out := new(KafkaAccessQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaAccessQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAccessQuerySpec) DeepCopyInto(out *KafkaAccessQuerySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapKeys != nil {
		in, out := &in.ConfigMapKeys, &out.ConfigMapKeys
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.EnvironmentVariableNames != nil {
		in, out := &in.EnvironmentVariableNames, &out.EnvironmentVariableNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AIAnalysisEnabled != nil {
		in, out := &in.AIAnalysisEnabled, &out.AIAnalysisEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAccessQuerySpec.
func (in *KafkaAccessQuerySpec) DeepCopy() *KafkaAccessQuerySpec {
	if in == nil {
		return nil
	}
	out := new(KafkaAccessQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaAccessQueryStatus) DeepCopyInto(out *KafkaAccessQueryStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.AccessingPods != nil {
		in, out := &in.AccessingPods, &out.AccessingPods
		*out = make([]PodAccessInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAccessQueryStatus.
func (in *KafkaAccessQueryStatus) DeepCopy() *KafkaAccessQueryStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaAccessQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAccessInfo) DeepCopyInto(out *PodAccessInfo) {
	*out = *in
	if in.DetectedBrokerEndpoints != nil {
		in, out := &in.DetectedBrokerEndpoints, &out.DetectedBrokerEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoCommit != nil {
		in, out := &in.AutoCommit, &out.AutoCommit
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalConfig != nil {
		in, out := &in.AdditionalConfig, &out.AdditionalConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]TopicInfo, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedTenants != nil {
		in, out := &in.AuthorizedTenants, &out.AuthorizedTenants
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedRoles != nil {
		in, out := &in.AuthorizedRoles, &out.AuthorizedRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecentProblems != nil {
		in, out := &in.RecentProblems, &out.RecentProblems
		*out = make([]ProblemDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAccessInfo.
func (in *PodAccessInfo) DeepCopy() *PodAccessInfo {
	if in == nil {
		return nil
	}
	out := new(PodAccessInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProblemDetail) DeepCopyInto(out *ProblemDetail) {
	*out = *in
	in.LastSeenTimestamp.DeepCopyInto(&out.LastSeenTimestamp)
	if in.BrokerLogSnippets != nil {
		in, out := &in.BrokerLogSnippets, &out.BrokerLogSnippets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProblemDetail.
func (in *ProblemDetail) DeepCopy() *ProblemDetail {
	if in == nil {
		return nil
	}
	out := new(ProblemDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicInfo) DeepCopyInto(out *TopicInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicInfo.
func (in *TopicInfo) DeepCopy() *TopicInfo {
	if in == nil {
		return nil
	}
	out := new(TopicInfo)
	in.DeepCopyInto(out)
	return out
}
