---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - accessmonitor.masorange.com
  resources:
  - kafkaaccessqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accessmonitor.masorange.com
  resources:
  - kafkaaccessqueries/finalizers
  verbs:
  - update
- apiGroups:
  - accessmonitor.masorange.com
  resources:
  - kafkaaccessqueries/status
  verbs:
  - get
  - patch
  - update
