---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmonitor.nachoperator.io
  resources:
  - certificatemonitors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmonitor.nachoperator.io
  resources:
  - certificatemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - certmonitor.nachoperator.io
  resources:
  - certificatemonitors/status
  verbs:
  - get
  - patch
  - update
