# permissions for end users to edit upgradeorchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: upgrade-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: upgradeorchestrator-editor-role
rules:
- apiGroups:
  - apps.nachoperator.io
  resources:
  - upgradeorchestrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nachoperator.io
  resources:
  - upgradeorchestrators/status
  verbs:
  - get
