{{- if .Values.ai.apikey }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-kafka-access-monitor-apikey
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  apiKey: {{ .Values.ai.apikey | quote }}
  team: {{ .Values.ai.team | quote }}
{{- end }}
